# Generated by Django 6.0.6 on 2026-07-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contactmessage_is_treated'),
    ]

    operations = [
        migrations.CreateModel(
            name='inscription_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('matriculle', models.CharField(max_length=12)),
                ('user_name', models.CharField(max_length=12)),
                ('pass_word', models.CharField(max_length=20)),
                ('is_treated', models.BooleanField(default=False)),
            ],
        ),
    ]
